services:
  api-tests-dev:
    build: .
    image: aceskaemilija/api-tests
    container_name: api-tests-dev
    volumes:
      - $PWD/test-reports/dev:/api-tests/mochawesome-report
    command: run BOOKS BOOKS_DEV
    networks:
      - sample-book-app-network-compose
  api-tests-stg:
    build: .
    image: aceskaemilija/api-tests
    container_name: api-tests-stg
    volumes:
      - $PWD/test-reports/stg:/api-tests/mochawesome-report
    command: run BOOKS BOOKS_STG
    networks:
      - sample-book-app-network-compose
  api-tests-prd:
    build: .
    image: aceskaemilija/api-tests
    container_name: api-tests-prd
    volumes:
      - $PWD/test-reports/prd:/api-tests/mochawesome-report
    command: run BOOKS BOOKS_PRD
    networks:
      - sample-book-app-network-compose

networks:
  sample-book-app-network-compose:
    external: true

# docker build -t api-tests . 
# docker run --rm --network=sample-book-app-network -v $PWD:/api-tests/mochawesome-report api-tests run BOOKS BOOKS_LOCAL
# docker run --rm --network=host api-tests run BOOKS BOOKS_LOCAL